spring:
  datasource:
    url: jdbc:mysql:///security?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cj.springsecurity.mapper: debug


server:
  port: 8081
